# Generated by Django 4.1.7 on 2023-05-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
